import type { VaultItem } from "./types";

export const MOCK_VAULT_ITEMS: VaultItem[] = [
  {
    id: "v1",
    title: "DATABASE_URL",
    value: "postgresql://user:secret@localhost:5432/app",
    maskedValue: "postgresql://••••••••@localhost:5432/app",
    description: "Main app database",
    category: "environment",
    tags: ["db", "prod"],
    projectId: "1",
    favorite: true,
    createdAt: "2025-03-01T10:00:00Z",
    lastUsed: "2025-03-12T08:00:00Z",
  },
  {
    id: "v2",
    title: "OPENAI_API_KEY",
    value: "sk-••••••••••••••••",
    maskedValue: "sk-••••••••••••••••",
    category: "tokens",
    tags: ["ai"],
    favorite: false,
    createdAt: "2025-02-15T12:00:00Z",
  },
  {
    id: "v3",
    title: "GitHub SSH config",
    value: "Host github.com\n  IdentityFile ~/.ssh/id_ed25519_github",
    maskedValue: "Host github.com\n  IdentityFile ~/.ssh/••••••••",
    category: "ssh",
    tags: ["git"],
    favorite: true,
    createdAt: "2025-01-10T09:00:00Z",
    lastUsed: "2025-03-12T07:30:00Z",
  },
  {
    id: "v4",
    title: "Stripe Secret Key",
    value: "sk_live_••••••••",
    maskedValue: "sk_live_••••••••",
    category: "apis",
    tags: ["payments"],
    projectId: "3",
    favorite: false,
    createdAt: "2025-02-20T14:00:00Z",
  },
  {
    id: "v5",
    title: "Redis URL",
    value: "redis://localhost:6379/0",
    maskedValue: "redis://localhost:6379/0",
    category: "databases",
    tags: ["cache"],
    favorite: false,
    createdAt: "2025-03-05T11:00:00Z",
  },
];
