import type { UniversityWorkspaceState } from "./types";

const today = new Date();
const todayYmd = `${today.getFullYear()}-${`${today.getMonth() + 1}`.padStart(2, "0")}-${`${today.getDate()}`.padStart(2, "0")}`;

export const UNIVERSITY_WORKSPACE_EMPTY_STATE: UniversityWorkspaceState = {
  config: null,
  semesters: [],
  courses: [],
  schedules: [],
  sessions: [],
  assignments: [],
  focusSessions: [],
  conflicts: [],
  stats: {
    activeCourses: 0,
    pendingAssignments: 0,
    classesToday: 0,
    credits: 0,
  },
  attendanceByCourse: {},
  gradeAveragesByCourse: {},
};

export const UNIVERSITY_WORKSPACE_MOCK_STATE: UniversityWorkspaceState = {
  config: {
    id: "mock-config",
    workspaceId: "mock-workspace",
    subtypeCode: "university",
    currentSemesterLabel: "2026-I",
    startDate: "2026-03-01",
    endDate: "2026-07-31",
    gradeScale: "0_100",
    creditGoal: 24,
    autoGenerateSessions: true,
    remindersEnabled: true,
    conflictDetectionEnabled: true,
    aiSummaryEnabled: true,
    onboardingCompleted: true,
    onboardingStep: 3,
  },
  semesters: [
    {
      id: "sem-1",
      workspaceId: "mock-workspace",
      name: "2026-I",
      startDate: "2026-03-01",
      endDate: "2026-07-31",
      isCurrent: true,
      creditGoal: 24,
    },
  ],
  courses: [
    {
      id: "course-1",
      workspaceId: "mock-workspace",
      semesterId: "sem-1",
      name: "Arquitectura de Software",
      professor: "Dra. Elena Soto",
      credits: 5,
      classroom: "A-302",
      courseType: "lecture",
      colorToken: "indigo",
      icon: "Blocks",
      sortOrder: 0,
      archived: false,
    },
    {
      id: "course-2",
      workspaceId: "mock-workspace",
      semesterId: "sem-1",
      name: "Bases de Datos Avanzadas",
      professor: "Ing. Mario Rivas",
      credits: 4,
      classroom: "Lab-2",
      courseType: "lab",
      colorToken: "emerald",
      icon: "Database",
      sortOrder: 1,
      archived: false,
    },
  ],
  schedules: [
    {
      id: "sch-1",
      courseId: "course-1",
      workspaceId: "mock-workspace",
      weekday: "monday",
      startTime: "09:00",
      endTime: "10:30",
      classroom: "A-302",
    },
    {
      id: "sch-2",
      courseId: "course-2",
      workspaceId: "mock-workspace",
      weekday: "monday",
      startTime: "10:00",
      endTime: "11:30",
      classroom: "Lab-2",
    },
  ],
  sessions: [
    {
      id: "session-1",
      workspaceId: "mock-workspace",
      semesterId: "sem-1",
      courseId: "course-1",
      scheduleId: "sch-1",
      sessionDate: todayYmd,
      startTime: "09:00",
      endTime: "10:30",
      classroom: "A-302",
      title: "Arquitectura de Software",
      notesHtml: null,
      notesJson: null,
      aiSummaryMock: null,
      generatedFromSchedule: true,
    },
  ],
  assignments: [
    {
      id: "asg-1",
      workspaceId: "mock-workspace",
      semesterId: "sem-1",
      courseId: "course-1",
      classSessionId: "session-1",
      title: "Documento de visión del proyecto",
      description: "Entregar versión v1 en PDF.",
      deadline: new Date(today.getTime() + 48 * 60 * 60 * 1000).toISOString(),
      priority: "high",
      status: "in_progress",
      attachments: [],
    },
  ],
  focusSessions: [],
  conflicts: [
    {
      day: "monday",
      courseId: "course-1",
      courseName: "Arquitectura de Software",
      conflictingCourseId: "course-2",
      conflictingCourseName: "Bases de Datos Avanzadas",
      startTime: "09:00",
      endTime: "10:30",
      conflictingStartTime: "10:00",
      conflictingEndTime: "11:30",
    },
  ],
  stats: {
    activeCourses: 2,
    pendingAssignments: 1,
    classesToday: 1,
    credits: 9,
  },
  attendanceByCourse: {
    "course-1": 88,
    "course-2": 92,
  },
  gradeAveragesByCourse: {
    "course-1": 86.4,
    "course-2": 90.2,
  },
};
